global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/q/metrics'

  - job_name: 'puntos'
    static_configs:
      - targets: ['service1:8081']
    metrics_path: '/q/metrics'

  - job_name: 'marketing'
    static_configs:
      - targets: ['service2:8082']
    metrics_path: '/q/metrics'

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/metrics'